apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sample-replicaset
  labels: 
    app: sample-app
    type: front-end
spec:
  template:
    metadata:
      name: sample-app-pod
      labels:
        app: sample-app
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end